# Generated by Django 5.1.4 on 2026-06-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('importer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('amount_base_minor', models.BigIntegerField()),
                ('fx_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('unequal', 'Unequal (exact amounts)'), ('percentage', 'Percentage'), ('share', 'Shares (ratio)')], max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='importer.importbatch')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='groups.member')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('amount_base_minor', models.BigIntegerField()),
                ('fx_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to='groups.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='importer.importbatch')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to='groups.member')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_minor', models.BigIntegerField()),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='groups.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('expense', 'member'), name='unique_member_per_expense_split')],
            },
        ),
    ]
